version: 2
updates:
  - package-ecosystem: 'npm'
    open-pull-requests-limit: 8
    directory: '/'
    versioning-strategy: 'increase'
    registries:
      - 'https://registry.npmjs.org'
      - 'https://registry.yarnpkg.com'
      - 'https://registry.pnpmjs.org'
    commit-message:
      prefix: 'fix'
      include: 'scope'
    schedule:
      interval: 'daily'
      time: '05:00'
      timezone: 'Asia/Ho_Chi_Minh'
