version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: 'increase'
    commit-message:
      prefix: 'fix'
      include: 'scope'
    schedule:
      interval: 'daily'
      time: '05:00'
      timezone: 'Asia/Ho_Chi_Minh'
