name: Review Dog

on:
  push:
    branches:
      - '**'
      - '!main'

concurrency:
  group: ${{ github.workflow }}-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    name: Review Dog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: reviewdog --diff="git diff main"
