name: ✨

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install package
        run: yarn
      - name: Check lint
        run: yarn lint
      - name: Run API in background
        run: |
          yarn build
          node dist/main > .log &
          echo $! > .pid
        env:
          SERVICE_HOST: 0.0.0.0
          SERVICE_PORT: 3000
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports['5432'] }}
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
          DB_AUTO_RUN_MIGRATIONS: 'false'
          DB_AUTO_SYNC: 'true'
          JWT_SECRET_KEY: top_secret
          JWT_EXPIRATION_TIME: 7d
      - name: Healthcheck API
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:3000/v1/healthz
          max-attempts: 10
          retry-delay: 5s
          retry-all: false
      - name: Run test
        run: yarn test:e2e
        env:
          API_URL: http://localhost:3000
          USER_EMAIL: user@test.com
          USER_PASSWORD: Abcd12345-
      - name: Show Log
        if: failure()
        run: cat .log
      - name: Kill API
        run: kill $(cat .pid)
        if: always()
